### ISSUE TITLE
Add "ffgmx.itp" to pure_TO

### ISSUE THREAD

**Issue by KasperBuskPedersen** [patrickfuchs/Lipid_Droplets#1]
Hi Patrick,

I really want to try out the UA TO parameters. The topology file refers to a "ffgmx.itp" file which is not present. Is this something you could share? :) 

Best regards,
Kasper

**Comment by KasperBuskPedersen** [comment]
This may have been a rather silly question. I found the following files on the gromacs ff page. Are these the one you used? 

Best, Kasper

[ffgmx_lipids.zip](https://github.com/patrickfuchs/Lipid_Droplets/files/5873673/ffgmx_lipids.zip)

**Comment by patrickfuchs** [comment]
Hi @KasperBuskPedersen, no worries it's no silly question 😉 ! Indeed, ffgmx.itp can be found on old versions of GROMACS (up to 4.5.* I think), it is now a deprecated force field since it was based on GROMOS 87 or so. It used to be the standard way to simulate [Berger lipids](http://dx.doi.org/10.1016/S0006-3495(97)78845-3) as implemented by Peter Tieleman and available on his [website](http://wcm.ucalgary.ca/tieleman/downloads). If you simulate TO only, or TO and lipids that is fine. If you plan later, to simulate some proteins with those parameters, you may want to use [Justin Lemkul's trick](http://www.mdtutorials.com/gmx/membrane_protein/02_topology.html) to make the file compatible with more recent GROMOS versions.
Anyway, thanks for the question, I will add a note for young scientists who never encountered ffgmx.
